quarkus.virtual-threads.enabled=true

quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE}
quarkus.datasource.username=${MYSQL_USERNAME}
quarkus.datasource.password=${MYSQL_PASSWORD}
quarkus.datasource.jdbc.min-size=0
quarkus.datasource.jdbc.max-size=8

quarkus.mybatis.mapper-locations=mapper
quarkus.mybatis.map-underscore-to-camel-case=true

quarkus.log.level=INFO
#SQL 日志
quarkus.log.console.level=DEBUG
#quarkus.log.category."com.qhr".level=DEBUG
quarkus.log.category."io.quarkus".level=INFO
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{2.}] (%t) %s%e%n
#HTTP 访问日志 暂时用不到
# 用于：
# 排查谁请求了哪个接口
# 看返回码分布，快速发现 404/500
# 排查网关、前端、爬虫、恶意请求
# 做审计和流量分析
#quarkus.http.access-log.enabled=true
#quarkus.http.access-log.pattern=%h %l %u %t "%r" %s %b
#13552835081
qcc-key=b859158058d645e498776ef16f64e03b
qcc-secretKey=34C5947A8D19584C3DD09669465C5292
#15932100412
#qcc-key=e9dcc17c80b940fcaff8e05d64ac973f
#qcc-secretKey=BD6C58A1C3A81234E380896B8E56BE49
#关闭quarkus 持续测试 功能
quarkus.test.continuous-testing=disabled
# 微信云文件解析 环境ID
wechat.cloud.env=prod-4gj7bacv12255db5