quarkus.virtual-threads.enabled=true

quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE}
quarkus.datasource.username=${MYSQL_USERNAME}
quarkus.datasource.password=${MYSQL_PASSWORD}
quarkus.datasource.jdbc.min-size=0
quarkus.datasource.jdbc.max-size=8

quarkus.mybatis.mapper-locations=mapper
quarkus.mybatis.map-underscore-to-camel-case=true
quarkus.log.level=INFO
quarkus.log.category."com.qhr".level=DEBUG
quarkus.log.console.level=DEBUG
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{2.}] (%t) %s%e%n
quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern=%h %l %u %t "%r" %s %b
qcc-key=b859158058d645e498776ef16f64e03b
qcc-secretKey=34C5947A8D19584C3DD09669465C5292
#qcc-key=e9dcc17c80b940fcaff8e05d64ac973f
#qcc-secretKey=BD6C58A1C3A81234E380896B8E56BE49
