quarkus.virtual-threads.enabled=true

quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE}
quarkus.datasource.username=${MYSQL_USERNAME}
quarkus.datasource.password=${MYSQL_PASSWORD}
quarkus.datasource.jdbc.min-size=0
quarkus.datasource.jdbc.max-size=8

quarkus.mybatis.mapper-locations=mapper
quarkus.mybatis.map-underscore-to-camel-case=true

#%dev.quarkus.log.category."org.apache.ibatis".level=DEBUG
#%dev.quarkus.log.category."com.qhr".level=DEBUG
